name: Clang-Tidy CI

on:
  # Run the workflow on every pull request to the main branch
  pull_request:
    branches:
      - main
  # Optionally, run the workflow on each push to the repository
  push:
    branches:
      - main

jobs:
  clang_tidy_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y clang-tidy cmake build-essential

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Clang-Tidy on all C++ files
        run: |
          cd build
          # Find all .cpp files in the repository and run Clang-Tidy on each
          for file in $(find ../ -name '*.cpp'); do
            clang-tidy "$file" -- -I../include -std=c++20
          done
